### ISSUE TITLE
[Bungee] Error dispatching event to listener

### ISSUE THREAD

**Issue by Chearful** [NamelessMC/Nameless-Plugin#24] opened 2016-12-24 02:21 UTC
I'm using the latest Bungeecord version available over at Spigot's Jenkins and the latest Nameless build on your Jenkins.

There are no errors on startup, but an error whenever a player joins the proxy.
Do you have any suggestions? Thanks. 
```
21:17:02 [INFO] [Chearful] <-> InitialHandler has connected>

21:17:03 [SEVERE] Dec 23, 2016 9:17:03 PM net.md_5.bungee.event.EventBus postWARNING: Error dispatching event PostLoginEvent(player=Chearful) to listener com.namelessmc.namelessplugin.bungeecord.player.PlayerEventListener@37654521java.lang.NullPointerException    at com.namelessmc.namelessplugin.bungeecord.player.PlayerEventListener.onPlayerJoin(PlayerEventListener.java:46)    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)    at java.lang.reflect.Method.invoke(Method.java:498)    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:505)    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:312)    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)    at java.lang.Thread.run(Thread.java:745)>
21:17:03 [WARNING] Event PostLoginEvent(player=Chearful) took 290,915,028ns to process!>
21:17:03 [INFO] [Chearful] <-> ServerConnector [lobby] has connected>```

**Comment by Chearful** [comment] 2016-12-24 12:48
Hi,

I've just downloaded the latest build and restarted my Bungee. Whilst the error 'Invalid API method' no longer displays in chat whenever a player joins, I'm still getting the same error, but with a bit more verbose this time!

```
07:46:13 [INFO] [Chearful] <-> InitialHandler has connected>

07:46:14 [INFO] [NamelessMC] Chearful is not contained in the Player Information File..>
07:46:14 [INFO] [NamelessMC] AddingChearful to the Player Information File.>
07:46:14 [INFO] [NamelessMC] AddedChearful to the Player Information File.>
07:46:14 [INFO] [NamelessMC] Detected that Chearful has changed his/her username!>
07:46:14 [INFO] [NamelessMC] Changing Chearfuls username.>

07:46:14 [SEVERE] Dec 24, 2016 7:46:14 AM net.md_5.bungee.event.EventBus postWARNING: Error dispatching event PostLoginEvent(player=Chearful) to listener com.namelessmc.namelessplugin.bungeecord.player.PlayerEventListener@2b48a640java.lang.NullPointerException    at com.namelessmc.namelessplugin.bungeecord.player.PlayerEventListener.userNameCheck(PlayerEventListener.java:132)    at com.namelessmc.namelessplugin.bungeecord.player.PlayerEventListener.onPlayerJoin(PlayerEventListener.java:49)    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)    at java.lang.reflect.Method.invoke(Method.java:498)    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:505)    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:312)    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)    at java.lang.Thread.run(Thread.java:745)>

07:46:14 [INFO] [Chearful] <-> ServerConnector [lobby] has connected>```

**Comment by partydragen** [comment] 2016-12-24 13:15
Thats because plugin is newer than website... That why i mean plugin should be created in braches

Because plugin is created for NamelessMC v1.0.15 api now and 1.0.15 is not released

**Comment by Chearful** [comment] 2016-12-24 13:21
Makes sense; any idea where I can found 1.0.15?

**Comment by IsS127** [comment] 2016-12-24 13:39
Can you check in you're playersInformation file if any content is created?

**Comment by Chearful** [comment] 2016-12-24 13:49
@IsS127 My playerInformation.yml is empty. In addition to this, messages.yml is not automatically created; I ended up having to create that file manually.

**Comment by IsS127** [comment] 2016-12-24 13:50
Ok ty. We will be working on this :)

**Comment by Chearful** [comment] 2016-12-24 13:51
Okay, thanks! Let me know if you need any additional information.

**Comment by IsS127** [comment] 2016-12-25 17:56
Download this build http://ci.namelessmc.com/jenkins/job/Nameless-Plugin/18/com.namelessmc$Bungeecord/
And check if the issue is solved :)

**Comment by Lmmb74** [comment] 2016-12-26 21:21
I checked and the issue is solved. So I am closing this.

**Closed by Lmmb74** 2016-12-26 21:21 UTC
Labels: bug
