### ISSUE TITLE
Invalid API method

### ISSUE THREAD

**Issue by YouTiao233** [NamelessMC/Nameless-Plugin#37] opened 2017-06-25 04:35 UTC
Q:Invalid API method
Minecraft Server: Bungeecord
Pre release 1
![image](https://user-images.githubusercontent.com/21272351/27513666-ea4edfda-59a1-11e7-98f0-82b0ca8323c9.png)
![image](https://user-images.githubusercontent.com/21272351/27513667-fd032460-59a1-11e7-9987-afae1d6f4a41.png)
https://pastebin.com/JXt1JLVR
REMOVED LINK DUE SECURITY!

**Comment by samerton** [comment] 2017-06-25 10:05
The error you are getting looks like it is caused by the SSL certificate not being valid.

As for the invalid API method error itself, that is expected as an extra parameter is required in the URL specifying exactly what you want to do.

**Comment by IsS127** [comment] 2017-06-25 16:52
Replace https to http

**Comment by IsS127** [comment] 2017-07-10 16:22
Closing this. Reopen if not solved

**Closed by IsS127** 2017-07-10 16:22 UTC
