### ISSUE TITLE
Could not pass event PlayerKickEvent to NamelessMC v3.4.0

### ISSUE THREAD

**Issue by DexterSK** [NamelessMC/Nameless-Plugin#344] opened 2023-07-17 05:43 UTC
`Could not pass event PlayerKickEvent to NamelessMC v3.4.0
java.lang.ClassCastException: class com.destroystokyo.paper.profile.CraftPlayerProfile cannot be cast to class org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile (com.destroystokyo.paper.profile.CraftPlayerProfile and org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile are in unnamed module of loader java.net.URLClassLoader @421faab1)
        at org.bukkit.craftbukkit.v1_20_R1.ban.CraftProfileBanList.isBanned(CraftProfileBanList.java:79) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at org.bukkit.craftbukkit.v1_20_R1.ban.CraftProfileBanList.isBanned(CraftProfileBanList.java:17) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.isBanned(CraftPlayer.java:1640) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at com.namelessmc.plugin.bukkit.BukkitEventProxy.onBan(BukkitEventProxy.java:47) ~[Nameless-Plugin-Spigot-3.4.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2472.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2011]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:554) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:510) ~[?:?]
        at org.spigotmc.RestartCommand.shutdownServer(RestartCommand.java:77) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:61) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:40) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2011]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by PadowYT2** [comment] 2023-07-17 06:54
Before making issues, make sure to join the [Discord Server](https://discord.gg/nameless). The answer:
"I believe there is a bug with Paper: https://github.com/PaperMC/Paper/issues/9455
Paper will need to fix it on their side"

**Comment by samerton** [comment] 2023-07-17 07:20
Duplicate of https://github.com/NamelessMC/Nameless-Plugin/issues/343

As Padow says, please update Paper to the latest version

**Closed by samerton** 2023-07-17 07:20 UTC

**Comment by Derkades** [comment] 2023-07-17 08:54
Indeed, this has been fixed as of a couple days ago in paper :)
